[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "F36295"

# Background color for the main content area.
backgroundColor = "#F0FF33"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#3183D1"

# Color used for almost all text.
textColor = "#03080C"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans-serif" #"serif"
